# Generated by Django 5.2.4 on 2025-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="route_bounds",
            field=models.JSONField(
                blank=True, help_text="Route bounding box for map fitting", null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="route_geometry",
            field=models.TextField(
                blank=True, help_text="Encoded polyline route geometry from Mapbox"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle_make",
            field=models.CharField(
                blank=True, help_text="Vehicle make (e.g., Toyota)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle_model",
            field=models.CharField(
                blank=True, help_text="Vehicle model (e.g., Camry)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle_year",
            field=models.CharField(blank=True, help_text="Vehicle year", max_length=4),
        ),
    ]
